/** Autogenerated by \`initGlobalsTs.ts\` */
export { };

declare global {
}

/**
 * @module
 * This module defines the structure of the FeatureFlagsRspack interface.
 * It is used by createDefaultFeatureFlags.ts and is read by initGlobalsTs.ts
 * to generate global type declarations for feature flags.
 */

export interface FeatureFlagsRspack {
	urlEnc: boolean;
	corsTesting: boolean;
	corsEmulation: boolean;
	integrityEmulation: boolean;
	encBodyEmulation: boolean;
	cachesEmulation: boolean;
	clearEmulation: boolean;
	supportSpeculation: boolean;
	rewriterHtml: boolean;
	rewriterXslt: boolean;
	rewriterJs: boolean;
	rewriterCacheManifest: boolean;
	supportLegacy: boolean;
	supportWorker: boolean;
	reqInterceptionCatchAll: boolean | string;
	aeroBrandingInProd: boolean;
	githubRepo: string;
	errLogAfterColon: string;
	debug: string;
	serverOnly?: string;
}