// Auto-generated by webidl2ts - https://wicg.github.io/shared-storage/
type SharedStorageResponse = string | FencedFrameConfig;
interface SharedStorageWorklet extends Worklet {
	selectURL(
		name: string,
		urls: Array<SharedStorageUrlWithMetadata>,
		options?: SharedStorageRunOperationMethodOptions,
	): Promise<SharedStorageResponse>;
	run(
		name: string,
		options?: SharedStorageRunOperationMethodOptions,
	): Promise<any>;
}
type RunFunctionForSharedStorageSelectURLOperation = (
	urls: Array<string>,
	data?: any,
) => Promise<number>;
interface SharedStorageWorkletGlobalScope extends WorkletGlobalScope {
	register(name: string, operationCtor: Function): undefined;
	readonly sharedStorage: SharedStorage;
	readonly privateAggregation: PrivateAggregation;
	interestGroups(): Promise<Array<StorageInterestGroup>>;
	readonly navigator: SharedStorageWorkletNavigator;
}
interface SharedStorageUrlWithMetadata {
	url: string;
	reportingMetadata?: any;
}
interface Window {
	readonly sharedStorage: SharedStorage;
}
interface SharedStorageModifierMethod {}
interface SharedStorageSetMethod extends SharedStorageModifierMethod {
	new (key: string, value: string, options?: SharedStorageSetMethodOptions);
}
interface SharedStorageAppendMethod extends SharedStorageModifierMethod {
	new (
		key: string,
		value: string,
		options?: SharedStorageModifierMethodOptions,
	);
}
interface SharedStorageDeleteMethod extends SharedStorageModifierMethod {
	new (key: string, options?: SharedStorageModifierMethodOptions);
}
interface SharedStorageClearMethod extends SharedStorageModifierMethod {
	new (options?: SharedStorageModifierMethodOptions);
}
interface SharedStorageModifierMethodOptions {
	withLock?: string;
}
interface SharedStorageSetMethodOptions
	extends SharedStorageModifierMethodOptions {
	ignoreIfPresent?: boolean;
}
interface SharedStorage {
	get(key: string): Promise<string>;
	set(
		key: string,
		value: string,
		options?: SharedStorageSetMethodOptions,
	): Promise<any>;
	append(
		key: string,
		value: string,
		options?: SharedStorageModifierMethodOptions,
	): Promise<any>;
	delete(
		key: string,
		options?: SharedStorageModifierMethodOptions,
	): Promise<any>;
	clear(options?: SharedStorageModifierMethodOptions): Promise<any>;
	batchUpdate(
		methods: Array<SharedStorageModifierMethod>,
		options?: SharedStorageModifierMethodOptions,
	): Promise<any>;
	selectURL(
		name: string,
		urls: Array<SharedStorageUrlWithMetadata>,
		options?: SharedStorageRunOperationMethodOptions,
	): Promise<SharedStorageResponse>;
	run(
		name: string,
		options?: SharedStorageRunOperationMethodOptions,
	): Promise<any>;
	createWorklet(
		moduleURL: string,
		options?: SharedStorageWorkletOptions,
	): Promise<SharedStorageWorklet>;
	readonly worklet: SharedStorageWorklet;
	length(): Promise<number>;
	remainingBudget(): Promise<number>;
	[Symbol.asyncIterator](): AsyncIterableIterator<[string, string]>;
	entries(): AsyncIterableIterator<[string, string]>;
	keys(): AsyncIterableIterator<string>;
	values(): AsyncIterableIterator<string>;
	forEach(
		callbackfn: (
			value: string,
			key: string,
			iterable: SharedStorage,
		) => void,
		thisArg?: any,
	): void;
}
interface SharedStoragePrivateAggregationConfig {
	aggregationCoordinatorOrigin?: string;
	contextId?: string;
	filteringIdMaxBytes?: number;
	maxContributions?: number;
}
interface SharedStorageRunOperationMethodOptions {
	data?: any;
	resolveToConfig?: boolean;
	keepAlive?: boolean;
	privateAggregationConfig?: SharedStoragePrivateAggregationConfig;
	savedQuery?: string;
}
interface SharedStorageWorkletOptions extends WorkletOptions {
	dataOrigin?: string;
}
interface HTMLSharedStorageWritableElementUtils {
	sharedStorageWritable: boolean;
}
interface HTMLIFrameElement extends HTMLSharedStorageWritableElementUtils {}
interface HTMLImageElement extends HTMLSharedStorageWritableElementUtils {}
interface RequestInit {
	sharedStorageWritable?: boolean;
}
interface SharedStorageWorkletNavigator {}
interface SharedStorageWorkletNavigator extends NavigatorLocks {}
interface LockManager {}
interface Lock {}
