/**
 * @module
 * This script generates a typescript file that exports an enum of all the API interceptors in AeroSandbox
 * It is automatically ran when AeroSandbox is built with `npm run build`
 * This script can be used as an individual CLI app with `npm run initApis`
 */

// This is already defined in the global scope of Node, but not for Deno
import { argv } from "node:process";
import * as path from "node:path";
import { access, mkdir } from "node:fs/promises";
import { writeFileSync } from "node:fs";
import * as fs from "node:fs";

import { createApiInterceptorIteratorNodeSync } from "../build/createApiInterceptorIterator";
import { ok, err, Result } from "neverthrow";

/**
 * Creates a types file that exports an enum of all the API interceptors in AeroSandbox
 * @param output Where to place the file
 * @param distDir Where the dist dir should be created
 * @param logStatus Should messages be logged?
 * @param debugMode Enable verbose logging for the API interceptor iterator
 */
export default function initApis(
	output = "../types/dist/apis.d.ts",
	distDir: string | null | undefined = path.resolve(
		__dirname,
		"..",
		"types",
		"dist",
	),
	logStatus = true,
	debugMode = false
): Result<void, Error> {
	const apiGlobalProps: string[] = Array.from(
		createApiInterceptorIteratorNodeSync(undefined, undefined, debugMode),
	).map((aI) => aI.globalProp);

	try {
		if (distDir) initDist(distDir, logStatus);
		fs.mkdirSync(path.dirname(output), { recursive: true });
		const contents =
			`// Autogenerated by \`initApis.ts\`\nexport enum APIBitwiseEnum {\n${apiGlobalProps.join(",\n")
			}\n};`;
		writeFileSync(output, contents, {
			flag: "w",
		});
		if (logStatus) {
			console.info(
				`Successfully wrote the API Bitwise Enum to ${output} with contents: \n${contents}`,
			);
		}
		return ok(undefined);
	} catch (error) {
		return err(error as Error);
	}
}

function initDist(distDir: string, logStatus: boolean) {
	if (logStatus) console.log("Initializing the dist folder");
	access(distDir)
		// If dir doesn't exist
		.catch(() => createDistDir(distDir, logStatus));
}
function createDistDir(distDir: string, logStatus: boolean) {
	if (logStatus) console.log("Creating the dist folder");
	mkdir(distDir);
}

// If the file is being ran as a CLI script
/**
 * Detect if the script is being ran as a CLI script and not as a module
 */
const isCLI =
	// @ts-ignore: This is a Deno-only feature
	"Deno" in globalThis ? import.meta.main :
		// For Node CommonJS: check if the module is the main module
		require.main === module;
if (isCLI) {
	const output = process.env.OUTPUT;
	const distDir = process.env.DIST_DIR;
	const cliLogStatus =
		process.env.LOG_STATUS !== "true" && process.env.LOG_STATUS !== "false"
			? undefined
			: process.env.LOG_STATUS === "true";
	const cliDebugMode = process.env.DEBUG === "true";
	initApis(output, distDir, cliLogStatus, cliDebugMode);
}
