// @ts-expect-error: this type will be autogenerated
import type { APIBitwiseEnum } from "./dist/apis.js";

import type { ProxifiedObjType } from "$types/apiInterceptors";

export default interface ToBeDefined {
	// biome-ignore lint/suspicious/noExplicitAny: <explanation>
	defineProperty: any;
	window: {
		globalProp: string;
		// biome-ignore lint/suspicious/noExplicitAny: <explanation>
		browsingContext: any;
		proxyObject: ProxifiedObjType;
	};
}

/**
 * Key: name of API Interceptor
 * Value: the error when trying to load the API interceptor
 */
export type toBeDefinedErrsType = { [key: keyof APIBitwiseEnum]: Error };

declare global {
	// Options for escape traps
	interface EscapeWithKeywordOptions {
		keyword: string;
		maxDepth?: number;
		maxDepthChars?: number;
	}
	// Global escape method and keyword constants
	const ESCAPE_METHOD: "RegExp" | "JS";
	const ESCAPE_KEYWORD: "RegExp" | "JS";
	// Global keyword for escaping class members
	const AERO_CLASS_MEMBER_ESCAPE_KEYWORD: string;
	// Global build-time log after colon string
	const ERR_LOG_AFTER_COLON: string;
	// Global proxy namespace and config key
	const PROXY_NAMESPACE: string;
	const OUR_NAMESPACE: string;
	const CONFIG_KEY: string;

	// Build-time debug flag
	const DEBUG: boolean;

	// Add unregisterProtocolHandler to Navigator
	interface Navigator {
		unregisterProtocolHandler(scheme: string, url: string, title?: string): void;
	}

	// The conflicting $aero declaration that was here has been removed,
	// as a more complete global declaration for $aero exists elsewhere (likely referencing AeroGlobalType from types/$aero.d.ts)
}
export {};
